# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
    type: upstream
    upstream: "front:http"

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"

"https://api.{default}/":
    type: upstream
    id: graphqlEntrypoint
    upstream: "api:http"

"https://api.{default}/graphql":
    type: upstream
    id: graphqlSubscriptions
    upstream: "api:http"
    cache:
        enabled: false
